name: HerDays Telegram Notification

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Run Telegram Script
        run: node notify.js
